config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'recipes#index'
  resources :recipes

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
   belongs_to :recipe
   belongs_to :user
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :users, through: :favorites
  has_many :favorites
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :favorites
    has_many :recipes, through: :favorites
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  require 'json'
  require 'net/http'

  def index
    app_id = ENV["YUMMLY_APPLICATION_ID"]
    app_key = ENV["YUMMLY_APPLICATION_KEY"]
    @search = params[:search]
    if @search
      @recipes = Yummly.search(params[:search])
      url = "http://api.yummly.com/v1/api/recipes?_app_id=#{app_id}&_app_key=#{app_key}&q=#{@search}&requirePictures=true"
      encoded_url = URI.encode(url)
      uri = URI("#{encoded_url}")
      @results =  Net::HTTP.get(uri)
      @results = JSON.parse(@results)
      @results = @results["matches"][0..9]
  end
  end

  def show

    #@recipe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IsItVegan</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/index.html.erb
<%= form_tag recipes_path, :method => 'get' do %>
  <p>
  <%= text_field_tag :search, params[:search], placeholder: "Is It Vegan?" %>
  <%= submit_tag 'Search', :name => nil %>
  </p>
<%end%>
<ul>
<%if @search%>


<%@results.each do |result|%>
  <h1><%= result["recipeName"] %></h1>
  <p><%= result["ingredients"].join(', ')%>
  <img src = "<%=result["imageUrlsBySize"]["90"]%>"></p>
  <%end%>